### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by Joshix-1** [asozialesnetzwerk/an-website#19]
Pro:
- einfacher
- Sachen werden nicht dumm in der URL gespeichert

Contra:
- Ich will (ohne zu lügen) sagen können, dass die Seite keine Cookies nutzt

**Comment by Joshix-1** [comment]
Idee:
Einstellungsseite mit Knopf, der Sachen in Cookies speichert.

Einstellungen in URL werden den Einstellungen in Cookies bevorzugt.

**Comment by h4ckerle** [comment]
Für notwendige Cookies benötigst du keinen Consent...

**Comment by Joshix-1** [comment]
Ich weiß, hab ich auch nicht behaupted.
