### ISSUE TITLE
responsiveness issues with smartphones

### ISSUE THREAD

**Issue by Joshix-1** [asozialesnetzwerk/an-website#23]
issues to fix:
- [x] image sized fixed on error pages → code below header
- [x] "Das Asoziales Netzwerk" is too long for some devices
- [x] hamburger menu not always on screen on mobile phones (version page)
- [x] footer in too many lines (takes up too much space)

**Comment by h4ckerle** [comment]
Wie willst du den zweiten Punkt fixen?

**Comment by Joshix-1** [comment]
Scrollen? besseres abschneiden? 
Folgendes verhinden:
![2021-09-08_22-59](https://user-images.githubusercontent.com/57299889/132584764-ba7a873c-ff8b-460e-ac9b-6ca942783464.png)

**Comment by h4ckerle** [comment]
Müsste nicht reines centern das Problem fixen?

**Comment by Joshix-1** [comment]
Centern von was?
Mach einen PR

**Comment by h4ckerle** [comment]
Macht es das besser? 
![image](https://user-images.githubusercontent.com/76652420/132587580-2ba400c5-023e-4d42-ab97-f3fb965d7889.png)

**Comment by Joshix-1** [comment]
Das sieht nicht besser aus. Man müsste den Text in eine Zeile forcen. Abgesehen davon sieht der Titel links-bündig besser aus.

**Comment by Joshix-1** [comment]
https://joshix.asozial.org/100.html das Bild hier ist nervig. @Guerteltier hat Breite und Höhe des Bildes fix gemacht, damit  der Schriftzug nicht sichtbar ist. Jetzt ist das halt unresponsive.

**Comment by Joshix-1** [comment]
https://github.com/asozialesnetzwerk/an-website/commit/7bb5e77a73d92cb5ef8dadcc72b79a202f240854 fixed some issues
