### ISSUE TITLE
Quotes-Page

### ISSUE THREAD

**Issue by Joshix-1** [asozialesnetzwerk/an-website#39]
- [x] create page
- [x] add filter for next quotes
- [x] allow rating
- [x] add info page to show information about quotes and authors
- [x] add quote to report button
- [x] add create page
- [x] fix issues with, voting: doesn't work reliable
- [x] fix issue, when upvoting and then downvoting (counts as +0, but displays as -1)
- [x] navigate with arrow keys
- [x]  vote with keyboard
- [x] fix quote bg overlaying over image
- [x] improve design on mobile (have to zoom out)
- [x] fix error with: https://asozial.net/zitate/info/a/495/
- [x] image downloading??
- [x] improve image (add rating)
- [x] add url or something to image, so people know where to look for it
- [x] share with more sites than twitter (https://github.com/mxstbr/sharingbuttons.io ?)
- [x] add query param to remove host name from image
- [x] save ratings in redis; not in cookie
- [x] don't show rating at first, only show when already voted
- [x] ask for cookie consent (or atleast inform users about the cookie usage)

**Comment by binarynoise** [comment]
Tooltips are misplaced
![grafik](https://user-images.githubusercontent.com/50302352/145277467-ce30ee09-3f34-4dc4-aa21-4aa49cddb8ad.png)

**Comment by Joshix-1** [comment]
misplaced tooltips are fixed. thx
