### ISSUE TITLE
404 bei https://asozial.org/mathe-spiel/

### ISSUE THREAD

**Issue by binarynoise** [asozialesnetzwerk/an-website#49]
![grafik](https://user-images.githubusercontent.com/50302352/145276208-b59293e8-500b-44e7-bf87-78fc1d3ff407.png)

**Comment by Joshix-1** [comment]
Das ist auf https://github.asozial.org/Mathe-Spiel/ zu finden. Weiß noch nicht, ob ich das hier hinzufügen will.

**Comment by binarynoise** [comment]
Mmh, ich weiß auch leider nicht mehr, wie ich dort hingekommen bin, ich meine aber, ich hätte nur einen Link geklickt und wurde dann falsch verwiesen

**Comment by Joshix-1** [comment]
Der Link war auf https://github.asozial.org

**Comment by binarynoise** [comment]
Andererseits: wieso ist der Link bei Google indiziert:
https://www.google.com/search?hl=de&q=%22asozial.org%2Fmathe%2Dspiel%22

**Comment by binarynoise** [comment]
> Der Link war auf [github.asozial.org](https://github.asozial.org)

Heißt, war und ist nicht mehr? Ist schon gefixt?

**Comment by Joshix-1** [comment]
Genau. Deshalb ist der auch bei Google indiziert.

**Comment by binarynoise** [comment]
Dann ist ja jetzt wieder alles im Lot.
Aber eigentlich hätten die mitbekommen müssen, dass die Seite nicht existiert. Der Server liefert ja auch 404 als Status-Code.
