### ISSUE TITLE
Change text on quote site

### ISSUE THREAD

**Issue by Moritz448** [asozialesnetzwerk/an-website#89]
At the quote site, for example [https://asozial.org/zitate/96-766?r=w](https://asozial.org/zitate/96-766?r=w)
There is a button "Teile in sozialen Netzwerken"
I would change it to "Teilen in asozialen Netzwerken"

**Comment by Joshix-1** [comment]
They call themselves „sozial“, we call ourselves „asozial“. We are the opposite of them.

**Comment by Moritz448** [comment]
But after the kangaroos theory, the social networks are truly asocial, and so the only truly social network can be ours, the asocial network
